# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

ROF <- function(src, dst, lambda, tau, iter, height, width, channel) {
    invisible(.Call('TotVar_ROF', PACKAGE = 'TotVar', src, dst, lambda, tau, iter, height, width, channel))
}

TVL1 <- function(src, dst, lambda, tau, iter, height, width, channel) {
    invisible(.Call('TotVar_TVL1', PACKAGE = 'TotVar', src, dst, lambda, tau, iter, height, width, channel))
}

SobelOperator <- function(src, dst, height, width, channel) {
    invisible(.Call('TotVar_SobelOperator', PACKAGE = 'TotVar', src, dst, height, width, channel))
}

HuberROF <- function(src, dst, alpha, lambda, tau, iter, height, width, channel) {
    invisible(.Call('TotVar_HuberROF', PACKAGE = 'TotVar', src, dst, alpha, lambda, tau, iter, height, width, channel))
}

Inpaint <- function(src, dst, lambda, tau, iter, height, width, channel) {
    invisible(.Call('TotVar_Inpaint', PACKAGE = 'TotVar', src, dst, lambda, tau, iter, height, width, channel))
}

RealTime <- function(src, dst, alpha, lambda, tau, cartoon, iter, height, width, channel) {
    invisible(.Call('TotVar_RealTime', PACKAGE = 'TotVar', src, dst, alpha, lambda, tau, cartoon, iter, height, width, channel))
}

